arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

gripper_controller:
  action_ns: follow_joint_trajectory
  default: True
  type: position_controllers/JointTrajectoryController
  joints:
    - robotiq_85_left_knuckle_joint